version: '3'
services:
  micro:
    image: micro/micro
    container_name: micro
    command: server
    ports:
      - "8080-8081:8080-8081/tcp"
      - "2111-2115:2111-2115/tcp"
    environment:
      - MICRO_LOG_LEVEL=debug
    networks:
      - micro

  database-postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      TZ: PRC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/init_extensions.sql:/docker-entrypoint-initdb.d/init_extensions.sql
    networks:
      - micro
    restart: unless-stopped

volumes:
  users:
  database_postgres:

    # Networks to be created to facilitate communication between containers
networks:
  micro:
    external: true
